name: CI_GRFN

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: grfn

jobs:
  test:
    strategy:
      matrix:
        stack: ["2.13.1"]
        ghc: ["9.2.8"]
        cabal: ["3.10.2.1"]
        runner:
          - macOS-latest

        resolver:
          - lts-20.26  

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - id: cabal
        uses: ./
        with:
          working-directory: grfn
          stack-arguments: --resolver ${{ matrix.resolver }}
          cabal-arguments: --resolver ${{ matrix.resolver }}
          cache-prefix: ${{ matrix.resolver }}/

      - uses: actions/setup-haskell@v1 #.1.4
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}
          cabal-version: ${{ matrix.cabal }}
    
      - uses: actions/cache@v2
        name: Cache multiple paths
        env: 
          cache-name: cache-stack
        with:
          path: | 
            ~/.stack
            ~/src
            ~/app
            ~/test
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}- 
    

