name: CI_GRFN

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  myBuild:
    strategy:
      matrix:
        stack: ["latest"]
        ghc: ["9.2.8"]
        cabal: ["3.8.1.0"]
        ghcup: ["latest"]
        runner:
          - macOS-latest

        resolver:
          - lts-20.26  

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'
      with:
        fetch-depth: '0'

    - uses: actions/setup-haskell@v1 #.1.4
      name: Setup Haskell Stack
      with:
          stack-version: ${{ matrix.stack }}
          cabal-version: ${{ matrix.cabal }}
          ghcup-version: ${{ matrix.ghcup }}
    
    - uses: actions/cache@v2
      if: matrix.os  == 'macOS-latest'
      with:
       path: ~/.ghcup
       key: ${{ runner.os }}-${{ matrix.ghc }}-ghcup   

    - name: Echo World
      run: | 
         ls -al
         echo $GITHUB_REPOSITORY $GITHUB_WORKSPACE $GITHUB_EVENT_PATH $RUNNER_WORKSPACE
         echo
         env
    
    - name: Specific GHC
      run: |
        ghcup install ghc 9.2.8 
        ghcup set ghc 9.2.8

    - name: Build Binary
      run: |
        cabal build
        
