name: CI_GRFN

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  myBuild:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: ["2.15.3"]
        ghc:
          - "9.8.2"
          - "9.6.5"
        cabal: ["3.10.3.0"]
        ghcup: ["0.1.22.0"]
        runner:
          - macos-12
        resolver:
          - lts-22.23  

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        INITIAL_VERSION: 0.2.0
        PRERELEASE: true
      continue-on-error: true

    - uses: actions/setup-haskell@v1 #.1.4
      name: Setup Haskell Stack
      with:
          stack-version: ${{ matrix.stack }}
          cabal-version: ${{ matrix.cabal }}
    
    - name: Setup Z3
      id: z3
      uses: cda-tum/setup-z3@v1
      with:
            platform: macOS
            architecture: x64
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }} 
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-key }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}- 

    - name: Echo Runner environments
      run: | 
         ls -al
         echo $GITHUB_REPOSITORY $GITHUB_WORKSPACE $GITHUB_EVENT_PATH $RUNNER_WORKSPACE
         echo
         env
    
    - name: Specific GHC
      run: |
        ghcup install ghc ${{ matrix.ghc }}
        ghcup set ghc ${{ matrix.ghc }}
        ghc --version

    - name: Build Binary, Test and Documentation
      run: |
        make do_build do_test do_gendoc
