name: CI_GRFN

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: grfn

jobs:
  test:
    strategy:
      matrix:
        stack: ["2.13.1"]
        ghc: ["9.2.8"]
        cabal: ["latest"]
        ghcup: ["latest"]
        runner:
          - macOS-latest

        resolver:
          - lts-20.26  

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'
      with:
        fetch-depth: '0'

    - uses: actions/setup-haskell@v1 #.1.4
      name: Setup Haskell Stack
      with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}
          cabal-version: ${{ matrix.cabal }}
    
    - uses: actions/cache@v2
      if: matrix.os  == 'macOS-latest'
      with:
       path: ~/.ghcup
       key: ${{ runner.os }}-${{ matrix.ghc }}-ghcup   

    - name: Build Binary
      run: cabal build -I $GITHUB_WORKSPACE --print-directory
        
