name: CI_GRFN

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: grfn

jobs:
  test:
    strategy:
      matrix:
        runner:
          - macOS-latest

        resolver:
          - lts-20.26  # ghc-9.2

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - id: cabal
        uses: ./
        with:
          working-directory: grfn
          stack-arguments: --resolver ${{ matrix.resolver }}
          cabal-arguments: --resolver ${{ matrix.resolver }}
          cache-prefix: ${{ matrix.resolver }}/

      - if: ${{ runner.os == 'macOS-latest' }}
        run: |
          [[ "${{ steps.cabal.outputs.compiler }}" = "ghc-9.2.8" ]]
          [[ "${{ steps.cabal.outputs.compiler-version }}" = "9.2.8" ]]

